# Generated by Django 4.0 on 2022-02-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=40)),
                ('Student_School', models.IntegerField()),
                ('Student_RollNo', models.IntegerField()),
                ('Student_Std', models.IntegerField()),
                ('Location', models.CharField(max_length=30)),
            ],
        ),
    ]
